--- #YAML:1.0
name: Class-FakeAttributes
version: 0.01
license: artistic
distribution_type: module
requires:
  NEXT: 0.60
  perl: 5.6.0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Class::FakeAttributes:
    file: lib/Class/FakeAttributes.pm
    version: 0.01
generated_by: Module::Build version 0.19
